# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

variables:
  projectName: shakl
  imageName: '$(projectName)'
  registryServerName: '.azurecr.io'
  registryLogin: ''
  registryPassword: ''


steps:
- script: docker build -f Dockerfile -t $(registryServerName)/$(imageName):$(build.buildId) -t $(registryServerName)/$(imageName):latest .
  displayName: 'docker build'

- script: |
    docker login $(registryServerName) -u $(registryLogin) -p $(registryPassword)
    docker push $(registryServerName)/$(imageName):$(build.buildId)
    docker push $(registryServerName)/$(imageName):latest
  displayName: 'docker push'
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))  

- task: HelmInstaller@0
  displayName: 'Install Helm'
  inputs:
    helmVersion: 2.12.1  

- bash: |
    helm package --version $(build.buildId) --destination $(build.artifactStagingDirectory) $(system.defaultWorkingDirectory)/charts/$(projectName)
  displayName: 'helm package'
  
